### ISSUE TITLE
platformio.ini file for building from the command line

### ISSUE THREAD

**Issue by bertrik** [CorBer/teensy_batdetector#1]
Is there a platformio.ini file to build from the command line?

If not, are you interested in me trying to build such a file?
Building from the command line has some advantages:
* easier to see compile warnings (not so easy to see on Arduino IDE)
* you can automate the build process, e.g. using github actions and get immediate feedback if something breaks
* builds are more reproducible, everything is contained in the config file, no need to set "special" switches in the IDE or have complicated instructions for the tool chain setup.

**Comment by CorBer** [comment]
Hi Betrik,

I will supply a simple platformio.ini file in the next development update. But I will also share the arduino setup, most users of Teensy are compiling using the Arduino IDE so its logical to support that.

This is  preview of my current platformio.ini

[env:teensy36]
platform = https://github.com/platformio/platform-teensy.git
board = teensy36
board_build.f_cpu = '72'000'000'
framework = arduino
build_flags = -Wl,--print-memory-usage 
lib_deps =  milesburton/DallasTemperature@^3.9.1

; commented out for Teensy 4.1
; [env:teensy41]
; platform =teensy
; ; https://github.com/platformio/platform-teensy.git
; board = teensy41
; framework = arduino
; build_flags = -Wl,--print-memory-usage   
; lib_deps = milesburton/DallasTemperature@^3.9.1

cheers
Cor
